# Generated by Django 5.2.10 on 2026-02-02 18:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.TextField(default='en')),
                ('location', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4')], default='P4', max_length=2)),
                ('urgency_score', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('medical', 'medical'), ('fire', 'fire'), ('trapped', 'trapped'), ('shelter', 'shelter'), ('food', 'food'), ('water', 'water'), ('mental', 'mental'), ('other', 'other')], default='other', max_length=20)),
                ('escalation_needed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'active'), ('assigned', 'assigned'), ('resolved', 'resolved')], default='active', max_length=20)),
                ('assigned_to', models.TextField(blank=True, null=True)),
                ('last_message', models.TextField(blank=True, null=True)),
                ('triage_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_text', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_source', models.TextField(blank=True, default='fallback', null=True)),
            ],
            options={
                'db_table': 'cases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('user', 'user'), ('assistant', 'assistant')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'messages',
                'managed': False,
            },
        ),
    ]
